language: rust
branches:
  only:
    - master
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo check --all --tests --benches
  - cargo test --all
  - cd trie-db && cargo check --no-default-features && cd ..
  - cd memory-db && cargo check --no-default-features && cd ..
  - cd trie-root && cargo check --no-default-features && cd ..
