language: rust
branches:
  only:
    - master
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo check --all --tests --benches
  - cargo test --all
  - cd check_no_std && cargo check --no-default-features && cd ..
